name: Build and deploy

on:
  push:
    branches:
      - main
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
        source-url: https://nuget.pkg.github.com/balta-io/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    
    - name: Add GitHub Packages Source
      run: dotnet nuget add source https://nuget.pkg.github.com/balta-io/index.json -n github -u andrebaltieri -p ${{secrets.BALTA_PACKAGES_TOKEN}} --store-password-in-clear-text

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Create the Package
      run: dotnet pack --configuration Release

    - name: Publish
      run: dotnet nuget push "bin/Release/*.nupkg" -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/balta-io/index.json --skip-duplicate